name: Agendar refeições no SUAP
on:
  schedule:
    - cron: '30 11 * * 1-5'  # Executa de segunda a sexta-feira às 08:30
  workflow_dispatch: 

jobs:
  suap_meals_script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SUAP_USERNAME: ${{ secrets.SUAP_USERNAME }}
          SUAP_PASSWORD: ${{ secrets.SUAP_PASSWORD }}
        run: |
          python -m suap_meals.main
